### ISSUE TITLE
API: re-introduce the errors endpoint

### ISSUE THREAD

**Issue by els0r** [els0r/goProbe#178]
In v3, there is an endpoint that allows you to inspect what kind of capture errors were encountered. Re-activate it and provide an `errors` command in the process in `gpctl`.

DoD:

- [x] Replace errMap with more efficient / tailored concept
- [x] Rename "errors" to something else ("decoding failures"?)
- [x] Drop anything not required anymore (e.g. `the last %d packets could not be processed / parsed`)
- [x] Adapt metrics (overall error counter) accordingly (increment counts during rotation / lock only)
- [x] ~errors command for capture~ Extend capture status with parsing error counts
- [x] endpoint in goProbe's API
- [x] Extend `status` command in `gpctl` to support extended info with parsing errors

**Comment by fako1024** [comment]
@els0r Before we fully indulge in this, can we go a more pragmatic approach first and quickly compile in a simple log line for the individual errors and run that on the affected host(s). Why? Because:

- I'd really like / need to know what errors we see here _asap_ (it could be just fragmentation warnings, in which case EZ, but it could also be a fundamental issue with slimcap, in which case I should probably start investigating / fixing _now_ to hold the deadline).
- I think we should reconsider the current error map / handling approach before wrapping an API around it. Check out the code, after removing the fragmentation "error" we basically only have two distinct error options (from `ParsePacket()`, `ErrPacketTruncated` and `ErrInvalidIPHeader`) that may end up in that map. Everything else outside the parsing would trigger processing to be terminated / the interface to be restarted (which is a case for logging, not for error counting).

You see where I'm going with that? I think aside from the first point (which is just finding out what bugs us _now_) we should replace the rather generic map (which is a PITA to handle in an API anyway because you need locking and all the blabla) and the global counter by two individual counters for the two possible errors and track / reset them (and the overall number of errors is replaced by, well, the sum of both) and expose _those_ in the API (which of course totally makes sense to have in `gpctl`).

**Comment by els0r** [comment]
After handling the fragmentation errors, there is very little need for this at the moment, which is why I removed the v4 milestone. After 30 Billion packets captured, not a single error was observed.

This can be tackled out-of-band.

**Comment by fako1024** [comment]
@els0r Although not strictly necessary for v4, this has been bothering me too much to let it slide. I've restructured the parsing error handling from the ground up, now tracking it with a compile-time static table struct (which is still flexible enough to allow us to extend with more parsing errors in the future, if required) and uses `errnos` instead of the interface type `error` (because it's faster and for the limited cardinality of errors we may encounter just a perfect fit).
Errors are now also accessed together with all other stats during rotation only, so no races while still maximizing performance. Since it's such a trivial counter structure now I'm simply handing it down together with the other `CaptureStats`, so it's readily available in the API without any additional routes and at no extra cost. I've also aligned the drop counter to count the totals since start just like we do with all other counters. And finally I've extended `gpctl` to support an extended mode for `status` that prints the error counters if set:
```
└─ $ ▶ ../gpctl/gpctl --server.addr=127.0.0.1:3005 status -e

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                         Interface Statuses                                                          │
├─────────────┬──────────┬────────────┬───────────┬─────────────┬─────────┬───────────┬────────┬───────────────────┬──────────────────┤
│             │    total │            │     total │             │   total │           │ active │            parsing errors            │
│ iface       │ received │ + received │ processed │ + processed │ dropped │ + dropped │    for │ invalid IP header │ packet truncated │
├─────────────┼──────────┼────────────┼───────────┼─────────────┼─────────┼───────────┼────────┼───────────────────┼──────────────────┤
│ enp45s0u1u1 │  13.98 k │    12.13 k │   13.98 k │     12.13 k │  0.00   │    0.00   │   5m6s │            0.00   │           0.00   │
│ lo          │ 130.00   │    20.00   │  120.00   │     20.00   │  0.00   │    0.00   │   5m6s │            0.00   │           0.00   │
│ virbr0      │   0.00   │     0.00   │    0.00   │      0.00   │  0.00   │    0.00   │   5m6s │            0.00   │           0.00   │
╰─────────────┴──────────┴────────────┴───────────┴─────────────┴─────────┴───────────┴────────┴───────────────────┴──────────────────╯

Runtime info:

            Running since: 2023-08-23 10:04:33 (5m6s ago)
  Last scheduled writeout: 2023-08-23 10:05:00 (4m40s ago)

Totals:

    Packets
       Received: 14.11 k / + 12.15 k
      Processed: 14.10 k / + 12.15 k
        Dropped: 0.00   / + 0.00
```
