### ISSUE TITLE
global-query

### ISSUE THREAD

**Issue by els0r** [els0r/goProbe#43]
Distributed querying for goQuery, aggregating `results.Result` structures. This allows to run queries and flow aggregations against a global fleet which has goProbe/goQuery deployed.

**Comment by els0r** [comment]
I will overwrite the branch from #43 and overwrite it. Too much changed under the hood. I've saved the relevant bits in `global-query`.

Way to go about this:

- [ ] introduction of the `query.Executor` interface, which `goDB` will implement for use in`goQuery` as well as modules inside the `global-query` tool
- [ ] properly separate query results and goDB (`global-query` myst not import `goDB`)
- [ ] put together the `global-query` tool

**Comment by els0r** [comment]
Will start progress next week

**Comment by els0r** [comment]
Saw https://github.com/els0r/goProbe/actions/runs/4613869362/jobs/8156300674, which seems unrelated to this issue, but still needs to be investigated.

**Comment by els0r** [comment]
@fako1024 : need help with testing the very first version of `global-query`. Would be glad if you could give this a spin on your sensors with:

- [ ] compile goProbe from branch https://github.com/els0r/goProbe/tree/43-global-query and deploy on sensor fleet
- [ ] create the appropriate config to reach sensor fleet (see https://github.com/els0r/goProbe/blob/43-global-query/cmd/global-query/api-client-querier.yaml for example)

Then, run queries with the tool with
```bash
go run cmd/global-query/main.go --config cmd/global-query/local-config.yaml --hosts.querier.config cmd/global-query/api-client-querier.yaml -q <comma-separated-host-list> <goquery args>
```

**Comment by fako1024** [comment]
Raised #94 and will take care of the race condition. As for the global query I'll gladly give it a shot today. :heart:

**Comment by fako1024** [comment]
Sidenote: This error message probably needs some "love":
```
└─ $ ▶ ./global-query 
Failed to read in config: Config File ".cmd" Not Found in "[/home/fako]"
```
As in: If neither config not command line parameters are there complain about that specifically (and I assume the `.cmd` without prefix is also unintentional)...

**Comment by els0r** [comment]
@fako1024 : this thing is going places. You can test with latest changes and should be able to get a result.

Will still need polishing, as well as the introduction of the `host` attribute during printing. But it's a start. Have fun!

**Comment by els0r** [comment]
@fako1024 : next iteration ready. 

- [ 
- [x] I'd expect the table to show the hostname (or ID) to indicate where the flow / row came from.
- [ ] Last version showed a log message on the receiving goProbe sensor whenever an API call came in. Did that behavior change in this version? Having an info level message for each API call is probably a good idea (to know who queries my data and when)...
- [x] Can you maybe rebase / merge current develop into the branch (it's still crashing from https://github.com/els0r/goProbe/pull/99 , which makes testing a bit more complicated 😛 )?

Will revise the request logging when switching API to gin. Agree with your observation. As for the rebase: that was done already.

**Comment by fako1024** [comment]
Next test looks awesome alrady:

- No more crashes
- Hostname displayed correctly
- All queries I've tested work (obviously that's just a very biased subset)
- Query speed / performance is good, even for raw queries with lots of flows (>100k), also no errors / API issues during such queries (will be interesting so see how we can merge that with #75 later)
- Sorting looks good, both for aggregate and raw queries

Kudos, this looks like an awesome first shot. Can't wait to take a look at the API for integration into other frameworks... :heart_eyes: !!!

Only remark: As for the HTTP client interaction [here](https://github.com/els0r/goProbe/blob/43-global-query/pkg/goprobe/client/client.go) I can recommend a cool & well maintained package from some dude (_nudge_) that simplifies handling of the HTTP client and makes the code more readable (and might also simplify extending the client functionality lateron because it already comes with a lot of features, even production-level tested client certificate handling and the likes). Just saying :wink:

**Comment by els0r** [comment]
Thanks for the feedback. Glad to see the results looking consistent. As for the `resolve` queries, those need a separate investigation.

Some other news:

- have yourself a distributed query server with the `server` command of `global-query` 😎 
- `httpc` is in. Thanks for the pointer

It doesn't end here. I'll move the single call part of `global-query` to `goQuery`. Why? Because that's the CLI tool we use to run queries. Since there's already a client for `global-query`. Means you don't have to duplicate much and learn to call a new tool. Only add one or two config parameters to goQuery and you're done. Will keep you posted.

**Comment by fako1024** [comment]
Nice! Moving the query stuff to `goQuery` sounds like a good plan. Basically being able to perform local and global queries (which use the same syntax / logic anyway) with a single tool is probably for the best.

On a different note though: With the recent changes of yesterday / today the query tool stopped working (independent of the server mode). Doing the same queries as yesterday I now get nothing (literally, no error, no feedback, just a return code of `1`, so something probably didn't work the way it should):
```
└─ $ ▶ ./global-query --config ./local-config.yaml --hosts.querier.config api-client-querier.yaml -q fw-1,fw-2 -i eth0 -n 10 talk_conv
fako @ fako-x1 /tmp/goProbe/cmd/global-query (43-global-query *)
└─ $ ▶ echo $?
1
```
Diving a little deeper I figured as much: In `cmd/global-query/cmd/root.go` error handling is incomplete (the error is never shown and we just exit):
```
func Execute() {
        err := rootCmd.Execute()
        if err != nil {
                os.Exit(3)
        }
}
```
Throwing the error at that place at least tells me what's going on:
```
unknown command "talk_conv" for "global-query"
```
Could it be that the `cobra` command logic has a conflict between the flags / arguments of `global-query` and `goQuery` now that you're trying to handle both in one binary?

**Comment by fako1024** [comment]
Also maybe a more fundamental question: What exactly is it that I can `POST` to the endpoint? I figured it should be something along the lines of `query.Args`, but no matter what I `POST` to `/_query` I get nothing (again, no error, no feedback) so it's a bit hard for me to test this properly. Can you maybe provide me with some pointers?

**Comment by els0r** [comment]
Interesting. Thanks for the feedback. Then, the latest commit messed up something.

The POST should get the query args and then return the result.

I'll look at it in the context of moving all the code in entrypoint to the appropriate routine in goQuery (which does the call using the global-query client).

Stay tuned

**Comment by els0r** [comment]
Thanks for all the testing so far!!!

As for proper feedback/error messages: that still needs a bit of love on the client side (I may need your help with regards to how `httpc` is best used for that).

The recent commit can somewhat be called MVP for the entire query system. It _should_ work on your machine. Invocation via `goQuery` works as follows:

```
./goQuery --query.server.addr <host>:<port> -i eth0 -f -5m -n 10 sip,dip -q a,b
```
or
```
./goQuery --config goquery-conf.yaml -i eth0 -f -5m -n 10 sip,dip -q a,b
```
The query server is started with
```
./global-query --config global-query-conf.yaml server --server.addr localhost:8888
```

Naturally, this system needs quite some testing in https://github.com/els0r/goProbe/issues/74 to make sure there are no known regressions/edge cases that aren't covered.

@fako1024 : if you can confirm that it's now working in your infrastructure, I'll open the PR.

**Comment by fako1024** [comment]
Alrighty, got it to run. Some feedback:

- [ ] `global-query` is still very quite when I enter wrong parameters (unrelated to error handling when querying). At first I forgot that the tool is now only the server and tried to submit the query again. Silently exited, no feedback (probably related / similar issue as #104 ).
- [ ] When performing the query with `goQuery` it ignores the `-n` parameter (but only when querying more than one host via the `-q` parameter :rofl:):
```
./goQuery --query.server.addr 127.0.0.1:8888 -i eth0 -f -10m -q fw-2 -n 10 sip,dip
...
Query stats          : displayed top 10 hits out of 10 in 16ms
###########################
./goQuery --query.server.addr 127.0.0.1:8888 -i eth0 -f -10m -q fw-1,fw-2 -n 10 sip,dip
...
Query stats          : displayed top 733 hits out of 733 in 21ms
```
I'm unsure if it's only that parameter but since I doubt that you manually re-coded every parameter chances are that more parameters might be affected that are not forwarded to the sensor host
- [ ] For readability it might make sense to add some more love to the `hostname` / `hostid` columns (let's face it: when using `goQuery` nobody really cares about the `hostid` :stuck_out_tongue:). Maybe we could make this configurable and by default only display the `hostname` in interactive mode? Or shorten the `hostid` like a commit hash by default?

One more, unrelated thing: Is the Go API for the server abstract enough already so that it can be integrated into other tools (use case: I happen to have a central control server already and don't want to deploy another binary / independent microservice - instead I just want to integrate the global query API into my existing tool)?

**Comment by els0r** [comment]
Thx! Will have a look at the open points.

As for your question if the Go API is abstract enough: I would say so - as long as you use `gin-gonic` as the API router 🤓. What I could imagine is to make the `server.postQuery` registration public.

**Comment by els0r** [comment]
Answer would be: not much work 😄 . As you said, you can create the query args programmatically and then run it using the global-query client's `Run` (or `Query`) method. That's it. Job done.

I'm assuming, the whole thing would use JSON under the hood, since you are not planning to display text to a user, but further process the information retrieved.

If you do want to display it to a user, take note of the following code inside `cmd/goQuery/commands/root.go`:
```
		// make sure that the hostname is present in the query type (and therefore output)
		// The assumption being that a human will have better knowledge
		// of hostnames than of their ID counterparts
		if queryArgs.Format == "txt" {
			if !strings.Contains(queryArgs.Query, types.HostnameName) {
				queryArgs.Query += "," + types.HostnameName
			}
		}
```
That's just adding the label `hostname` to the output in case a human operator is looking at the results.
